apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm
spec:
  selector:
    matchLabels:
      app: wasm
  template:
    metadata:
      labels:
        app: wasm
    spec:
      runtimeClassName: wasm
      containers:
      - name: hello-wasm
        image: dippynark/hello-wasm:v0.1.0
        imagePullPolicy: Always
